# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Ready to Reopen
email: matt@envoy.com
description: >- # this means to ignore newlines until "baseurl:"
  Return to the office guidelines for Envoy.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://readytoreopen.envoy.com" # the base hostname & protocol for your site, e.g. http://example.com
links:
  planning_doc: https://docs.google.com/document/d/1vt-zsQAv49pIi3u5kVx3z-96eRT8tzyHWlWXy77NUdE/edit
  floorplan: https://app.lucidchart.com/documents/edit/fa53b454-4dcd-41c9-8130-bd40292a6621/0_0
  asana: https://app.asana.com/share/envoy/rto-plan/78903225373695/1717f77f4eb45f1e0c0bd7f737e227f7
  slack: https://envoy.slack.com/archives/C012JE0RJCU

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-postcss
  - jekyll-purgecss
  - jekyll-redirect-from
  - jekyll-get-json

# Fetch data from our Google Sheet
jekyll_get_json:
  - data: phases
    json: "https://sheets.googleapis.com/v4/spreadsheets/1wQd772XHgXUodEa1hrsO-HLRIN-wWnZQepq0m-p64Nk/values/'Return+Phases'?key=AIzaSyCk7XKPyDQfZCoLPC84h9986LlJlw0a-vo&majorDimension=ROWS"
  - data: current_phases
    json: "https://sheets.googleapis.com/v4/spreadsheets/1wQd772XHgXUodEa1hrsO-HLRIN-wWnZQepq0m-p64Nk/values/'Current+Phases'?key=AIzaSyCk7XKPyDQfZCoLPC84h9986LlJlw0a-vo&majorDimension=ROWS"

collections:
  phases:
    output: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
